[package]
name = "graph-visualizer"
version = "0.1.0"
edition = "2021"
authors = ["OscarGomez-jpg"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
macroquad = "0.4.4"